### ISSUE TITLE
Remove event listeners on disconnect

### ISSUE THREAD

**Issue by keyurshah** [calebporzio/project-x#19]
It might be out of the scope of the project, but wondering of the usefulness to remove event listeners on disconnect? 

If using with turbolinks, pjax or unpoly, it seems there's a chance for a memory leak with stranded event listeners.

And if project-x is used in a turbolinks type of environment, would it be helpful to have init(), connect() and disconnect() functions that can sit inside the x-data function?

**Comment by calebporzio** [comment]
yeah, all good points.

Question:
If an element has a listener attached and then is removed from the DOM by let's say Turbolinks, is the event listener still held in memory? I would think the browser would take care of that for us?

**Comment by keyurshah** [comment]
I thought I read an article yesterday that said if the removed element was being referenced elsewhere, that it would not remove the listener. 

I'm having trouble finding that, so will close the issue unless I find it again. Hopefully modern browsers are taking good care of it. 

Thanks!

**Comment by stefanfisk** [comment]
Since I was bored and curious I whipped up a super simple test that probably only works in Chrome: https://codepen.io/stefanfisk/pen/gOrEdGd

A component which is referenced from `window` listens to a custom event on `window` that is dispatched on a 100ms interval. When recieved, the component allocates a 1MiB `ArrayBuffer`. After 10sec the element is removed from the DOM, at which point the listener is removed.
